#!/usr/bin/env bash

set -e
[ -n "$GOST_PLUGIN_DEBUG" ] && set -x

if [ -z "$GOST_PLUGIN_ROOT" ]; then
  GOST_PLUGIN_ROOT="${HOME}/Library/Application Support/ShadowsocksX-NG/gost"
fi

colorize() {
  if [ -t 1 ]; then printf "\e[%sm%s\e[m" "$1" "$2"
  else echo -n "$2"
  fi
}

# Checks for gost plugin root directory, and suggests to remove it for installing
if [ -d "${GOST_PLUGIN_ROOT}" ]; then
  { echo
    colorize 1 "WARNING"
    echo ": Can not proceed with installation. Kindly remove the '${GOST_PLUGIN_ROOT}' directory first."
    echo
  } >&2
    exit 1
fi

mkdir "${GOST_PLUGIN_ROOT}"
GOST_VERSION=2.11.5
curl -L "https://github.com/ginuerzh/gost/releases/download/v${GOST_VERSION}/gost-darwin-amd64-${GOST_VERSION}.gz" --output "${GOST_PLUGIN_ROOT}/gost.gz"
gunzip "${GOST_PLUGIN_ROOT}/gost.gz"
chmod +x "${GOST_PLUGIN_ROOT}/gost"

GOST_PLUGIN_NAME=gost-plugin-mwss
SS_PLUGINS_ROOT="${HOME}/Library/Application Support/ShadowsocksX-NG/plugins"
curl -L "https://github.com/lewangdev/ShadowsocksX-NG-GostPlugin/releases/download/v0.0.2/${GOST_PLUGIN_NAME}.gz" --output "${SS_PLUGINS_ROOT}/${GOST_PLUGIN_NAME}.gz"
gunzip "${SS_PLUGINS_ROOT}/${GOST_PLUGIN_NAME}.gz"
chmod +x "${SS_PLUGINS_ROOT}/${GOST_PLUGIN_NAME}"


echo "Gost plugin installed."

